# Common variable

dell_switch_cli_user: admin
dell_switch_cli_pass: admin

# Variables for VLT and VRRP Paramenters
vlt1_loopback: 10.10.10.1/32
vlt2_loopback: 10.10.10.2/32
leaf1_loopback: 10.10.10.20/32
vlt1_vlan: 10.1.1.252/24
vlt2_vlan: 10.1.1.253/24
vip_group: 200
vip: 10.1.1.254


gather_facts: no

cli:
  host: "{{ ansible_host }}"
  username: "{{ dell_switch_cli_user }}"
  password: "{{ dell_switch_cli_pass }}"
  timeout: 60
  port: 22
  transport: cli
